name: Pre-commit Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Cache uv dependencies
      id: cache-uv
      uses: actions/cache@v4
      with:
        path: /home/runner/work/_temp/setup-uv-cache
        key: pre-commit-uv-${{ hashFiles('pyproject.toml', 'uv.lock') }}
        restore-keys: |
          pre-commit-uv-

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: '3.12'

    - name: Cache pre-commit
      id: cache-precommit
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pre-commit
          .ruff_cache
        key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
        restore-keys: |
          pre-commit-

    - name: Install dependencies
      run: |
        uv sync --extra dev

    - name: Run pre-commit
      run: |
        uv run pre-commit run --all-files

    - name: Prune uv cache for CI
      run: |
        uv cache prune --ci
